### PR TITLE
Move away from WindowListener API and use menu typed action button

### PR DESCRIPTION
**Pull request by jobisoft**
This PR is probably huge, it is a days work and I tried to get done all of it but the commands API still needs some work. Will send a follow-up, if you accept this.

It uses WebExtension API where possible and completed multiple update steps:
- removed unused/old code
- locale conversion
- moved main control logic to the background script
- break out individual Experiments and move away from the overlay style
- WindowListener is only used for the options page, which still needs to be converted to HTML

The menu entries in the file menu moved to the tools menu.

The status bar support has been removed. Could be added again as a dedicated Experiment, but it is very non-WebExtension-ish and if it is not extremely important, you could think about dropping it for good.

The actionbutton does not (yet) provide a click action, its setting has been hidden.

### CODE REVIEW

**Comment by dillenger** [comment]
Wow, very nice, thank you very much, you spent a lot of time on this.
The only thing missing apart from the click action is the status bar panel.
It may be non-WebExtension-ish but it is the place I check what profile I'm in.
It's also the place I usually click to switch to another profile.

**Comment by jobisoft** [comment]
The "title bar" option to display the current profile is now showing the name as the name of the button:
image

That is not a plausible alternative?

The issue with the status bar is that we want to improve the UX for users, so that they know where to expect certain things. The status bar is currently not on track to be opened up for WebExtensions, because the UI team believes it is a poor experience for users, because it is not manageable if multiple add-ons inject there. For the toolbars we will get overflow containers and proper handling soon, something that is not doable in a standard way in the status bar. We can still do it, but I would like to see it being dropped.

What I forgot to add, is that this PR removes all requirements for a restart to have changed options take effect. I do not know if it was really needed, but there have been two or three mentions in the settings page, which I removed, because all updates propagate directly now.

**Comment by dillenger** [comment]
That's OK, I didn't notice it before, it only shows when "Show profile name in the title bar" is checked.
Unfortunately it also doesn't show when using icons only.

"In menus sort profiles alphabetically" still requires a restart, changing the profile icon color doesn't.

**Comment by jobisoft** [comment]
> "In menus sort profiles alphabetically"

oh, I broke that again. will fix it

**Comment by jobisoft** [comment]
> > "In menus sort profiles alphabetically"
> 
> oh, I broke that again. will fix it

fixed in https://github.com/dillenger/profile-switcher/pull/2

**Pull request merged**
